# Generated by Django 6.0.4 on 2026-04-17 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип материала')),
                ('defect_percentage', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Процент брака материала')),
            ],
            options={
                'verbose_name': 'Тип материала',
                'verbose_name_plural': 'Типы материалов',
            },
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Тип партнера')),
            ],
            options={
                'verbose_name': 'Тип партнера',
                'verbose_name_plural': 'Типы партнеров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование продукции')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Минимальная стоимость для партнера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длина упаковки')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина упаковки')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Высота упаковки')),
                ('weight_without_pack', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес без упаковки')),
                ('weight_with_pack', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес с упаковкой')),
                ('production_time', models.IntegerField(blank=True, null=True, verbose_name='Время изготовления (мин)')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Себестоимость')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип продукции')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициент типа продукции')),
            ],
            options={
                'verbose_name': 'Тип продукции',
                'verbose_name_plural': 'Типы продукции',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование партнера')),
                ('director', models.CharField(max_length=255, verbose_name='Директор')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Юридический адрес')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('partner_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.partnertype', verbose_name='Тип партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество продукции')),
                ('sale_date', models.DateField(verbose_name='Дата продажи')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partner', verbose_name='Партнер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Продажа партнеру',
                'verbose_name_plural': 'История продаж партнерам',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Старая цена')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Новая цена')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'История изменения цены',
                'verbose_name_plural': 'История изменения цен',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.producttype', verbose_name='Тип продукции'),
        ),
    ]
